### ISSUE TITLE
coloring is wrong in some contexts

### ISSUE THREAD

**Issue by c-cube** [ocaml/vim-ocaml#86] opened 2022-08-03 14:35 UTC
```ocaml
let f = fun () : unit ->
  if not @@ !foo then ()
```

gives:

![vim](https://user-images.githubusercontent.com/1274291/182635373-8e246692-7f0f-4756-9b97-44c880064ea8.png)

**Comment by Maelan** [comment] 2022-08-03 15:53
Unfortunately, the test cases (see last line of the screenshot in #76) signal `fun ... : t -> e` as a tough issue of the new type linter. The problem is that `->` is usually a part of a type expression, but in this specific syntax it *ends* the type expression… Solving this would require treating the `fun` keyword specially, I guess. I’m not sure how to do this without writing a pattern linter to some extent.

Is `fun ... : t -> e` an often used construction?

**Comment by c-cube** [comment] 2022-08-03 16:11
It's something I use from time to time…

I don't mean to be rude but if the new type linter is wildly incorrect on valid syntax (I have opened several issues already), I would rather keep the old one. Better syntax coloring might require tree-sitter with a valid OCaml grammar.

**Comment by Maelan** [comment] 2022-08-03 18:36
TBH I think it rather means that the type linter was merged too eagerly, my apologies for that. Of the issues you reported, one was a silly mistake, two (`exception E = F` and `type ... : t -> e`) were known shortcomings. I took the time to fix these two and it was easier than I anticipated; see the PR above.

I guess type linting should get decent when that PR is merged. The only known issue that remains is `(module S)`, which I believe to be solvable (and I unfairly blame the obscure module linting stuff for me not fixing it :-( ).

**Closed** 2022-08-04 10:28 UTC

**Comment by c-cube** [comment] 2022-08-04 13:02
Thank you!

@Maelan no worries, it's easier to get feedback this way :wink: . I do like the new colors (mostly in labels I think? Maybe it's my colorscheme).

**Comment by Maelan** [comment] 2022-08-04 14:17
Yeah, trying to highlight labels is what got me started with this. You can also highlight all types (as opposed to just the builtin ones) if you customize your setup a bit (see snippet in the original PR). I guess we’d better add an option for that (or just make it the default?).
